'use strict';

const assert=require('assert');
const fs=require('fs');
const path=require('path');

const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const pipelineCss=read('gui/pipeline.css');
const pipelineJs=read('gui/pipeline.js');
const indexHtml=read('gui/index.html');
const themeCss=read('gui/theme.css');
const workspaceCss=read('gui/workspace.css');
const pipelineInteractionsCss=read('gui/pipeline-interactions.css');
const crossoverCss=read('gui/crossover-filter.css');
const crossoverJs=read('gui/crossover-filter.js');
const mpgdCss=read('gui/mag-phase-gd-filter.css');
const mpgdJs=read('gui/mag-phase-gd-filter.js');
const targetCss=read('gui/target-export.css');
const typographyCss=read('gui/typography.css');
const bankSourceJs=read('gui/bank-file-source.js');
const bankFileJs=read('gui/bank-file.js');
const workspaceThemeJs=read('gui/pipeline-workspace-theme.js');
const wireInspectJs=read('gui/pipeline-wire-inspect.js');
const pipelineContextCss=read('gui/pipeline-context.css');
const targetExportJs=read('gui/target-export.js');

assert.match(pipelineCss,/\.measurement-preview\{[^}]*width:min\(1196px,calc\(100vw - 28px\)\)/);
assert.match(pipelineCss,/\.pipeline-strip \.pipeline-card\{[^}]*grid-template-columns:max-content 44px;/);
assert.match(pipelineCss,/\.measurement-node\{[^}]*width:min\(248px,calc\(100vw - 48px\)\);min-width:0;max-width:none/);
assert.match(pipelineCss,/\.bank-file-node\{[^}]*width:min\(248px,calc\(100vw - 48px\)\);height:194px;[^}]*grid-template-rows:35px 126px 31px/);
assert.match(pipelineCss,/\.bank-file-list\{[^}]*grid-template-rows:repeat\(3,42px\)/);
assert.match(pipelineCss,/\.bank-file-head\{[^}]*cursor:grab;user-select:none;touch-action:none/);
assert.match(pipelineCss,/\.measurement-file\.bank-file-row\{[^}]*height:42px;min-height:42px;grid-template-columns:minmax\(0,1fr\) 20px/);
assert.doesNotMatch(pipelineCss,/\.bank-file-swatch\{/);
assert.match(pipelineCss,/\.measurement-list\{width:100%;min-width:0;/);
assert.match(pipelineCss,/\.measurement-file\{[^}]*width:100%;min-width:0;[^}]*grid-template-columns:13px minmax\(0,1fr\) 20px;/);
assert.match(pipelineCss,/\.measurement-node\.is-selecting \.measurement-file\{grid-template-columns:13px 13px minmax\(0,1fr\) 20px\}/);
assert.match(pipelineCss,/\.measurement-file-info\{width:100%;min-width:0;max-width:none;[^}]*align-items:flex-start;text-align:left;/);
assert.match(pipelineInteractionsCss,/\.measurement-file\{[^}]*width:100%;min-width:0;max-width:100%;grid-template-columns:13px minmax\(0,1fr\) 20px;padding-right:26px/);
assert.match(pipelineInteractionsCss,/\.measurement-node\.is-selecting \.measurement-file\{grid-template-columns:13px 13px minmax\(0,1fr\) 20px\}/);
assert.match(pipelineInteractionsCss,/\.measurement-file-check,\.measurement-color,\.measurement-file-info,\.measurement-preview-button\{grid-column:auto\}/);
assert.doesNotMatch(pipelineInteractionsCss,/\.measurement-file\{[^}]*width:max-content/);
assert.match(pipelineCss,/\.measurement-preview-graph\{[^}]*height:min\(300px,calc\(100vh - 152px\)\)/);
assert.match(pipelineCss,/\.measurement-preview-meta\{[^}]*grid-template-columns:repeat\(5,max-content\);justify-content:center;/);
assert.match(pipelineCss,/\.measurement-preview-meta div\{[^}]*justify-content:flex-start;/);
assert.match(pipelineCss,/\.measurement-preview-head\{[^}]*cursor:grab;user-select:none;touch-action:none/);
assert.match(pipelineCss,/\.measurement-preview\.is-dragging \.measurement-preview-head\{cursor:grabbing\}/);
assert.match(pipelineCss,/@media\(max-width:700px\)\{\s*\.measurement-preview\{[^}]*width:calc\(100vw - 10px\)/);
assert.match(pipelineCss,/@media\(max-width:700px\)[\s\S]*?\.measurement-preview-graph\{height:min\(240px,calc\(100vh - 142px\)\)\}/);
assert.match(pipelineCss,/@media\(max-width:700px\)[\s\S]*?\.measurement-preview-meta\{grid-template-columns:repeat\(2,max-content\);justify-content:start;/);
assert.match(pipelineJs,/hexTint\(entry\.color,\.22\)/);
assert.match(pipelineJs,/const graphScale=Math\.max\(1,Math\.min\(1\.55,/);
assert.match(pipelineJs,/const previewMinFrequencyHz=20;/);
assert.match(pipelineJs,/const previewMaxFrequencyHz=20000;/);
assert.match(pipelineJs,/const magnitudeFill=ctx\.createLinearGradient\(0,T,0,B\);/);
assert.match(pipelineJs,/magnitudeFill\.addColorStop\(0,hexTint\(previewColor,\.28\)\)/);
assert.match(pipelineJs,/function clampPreviewPosition\(left,top\)/);
assert.match(pipelineJs,/function startPreviewDrag\(event\)/);
assert.match(pipelineJs,/previewHead\.addEventListener\('pointerdown',startPreviewDrag\)/);
assert.doesNotMatch(pipelineJs,/20000,50000/);
assert.match(indexHtml,/theme\.css\?v=compact-top-boundary-20260914-1/);
assert.match(indexHtml,/pipeline\.css\?v=static-wire-bank-palette-20260915-1/);
assert.match(indexHtml,/pipeline-context\.css\?v=static-wire-bank-palette-20260915-1/);
assert.match(indexHtml,/mag-phase-gd-filter\.css\?v=chrome-pc-motion-20260915-1/);
assert.match(indexHtml,/matching\/matching\.js\?v=chrome-pc-motion-20260915-1/);
assert.doesNotMatch(indexHtml,/pipeline-canvas-divider/);
assert.match(indexHtml,/workspace\.css\?v=welcome-canvas-no-art-20260913-1/);
assert.match(indexHtml,/pipeline-interactions\.css\?v=compact-measurement-rows-20260912-1/);
assert.match(indexHtml,/pipeline\.js\?v=chrome-pc-motion-20260915-1/);
assert.match(indexHtml,/pipeline-workspace-theme\.js\?v=forest-aurora-20260915-1/);
assert.match(indexHtml,/forest-aurora\.css\?v=forest-aurora-20260915-1/);
assert.match(indexHtml,/typography\.css\?v=independent-bank-reverse-wire-20260914-1/);
assert.match(indexHtml,/id="bankFileNode" data-source-node hidden/);
assert.match(indexHtml,/<strong>Bank File<\/strong>/);
assert.match(indexHtml,/<span>Neutral files<\/span>/);
assert.doesNotMatch(indexHtml,/bank-file-badge|>SOURCE</);
assert.match(indexHtml,/<strong>0° \/ 0 dB<\/strong>/);
assert.match(indexHtml,/bank-file-source\.js\?v=static-wire-bank-palette-20260915-1/);
assert.match(indexHtml,/bank-file\.js\?v=independent-bank-reverse-wire-20260914-1/);
assert.match(indexHtml,/<section class="page-view" data-view="welcome" hidden><\/section>/);
assert.doesNotMatch(indexHtml,/welcome-raptor|raptor-welcome-v1\.png/);
assert.match(workspaceCss,/\.workspace-canvas\[data-page="welcome"\]\{background:radial-gradient\(ellipse at 14% 12%,rgba\(216,190,67,\.16\)/);
assert.match(workspaceCss,/\.workspace-canvas\[data-page="welcome"\]::before\{opacity:\.82;[^}]*background-size:24px 24px,96px 96px,6px 6px,6px 6px/);
assert.doesNotMatch(workspaceCss,/\.welcome-raptor\{|\.welcome-hero\{/);

for(const source of [crossoverCss,mpgdCss]){
  assert.match(source,/--lineage-tint:rgba\(143,166,184,\.24\)/);
  assert.match(source,/--lineage-tint-soft:rgba\(143,166,184,\.12\)/);
}
for(const source of [crossoverJs,mpgdJs]){
  assert.match(source,/hexTint\(color,\.24\)/);
  assert.match(source,/hexTint\(color,\.12\)/);
}
assert.match(targetCss,/var\(--source-color\) 22%,#fff/);
assert.match(typographyCss,/--raptor-font-ui:system-ui,[^;]*"Noto Sans Thai",[^;]*"Leelawadee UI",Thonburi,Tahoma/);
assert.match(typographyCss,/\.workspace-shell \.measurement-file-name\{font-size:10\.5px/);
assert.match(typographyCss,/\.workspace-shell \.bank-file-name\{font-size:10\.5px/);
assert.match(typographyCss,/\.workspace-shell \.mpgd-phase-turn-panel\{font-size:9px/);
assert.match(pipelineJs,/getComputedStyle\(preview\)\.fontFamily/);
assert.doesNotMatch(typographyCss,/@import|@font-face|fonts\.googleapis/);
assert.match(bankSourceJs,/sampleRateHz:48000,fftSize:32768,maxFrequencyHz:24000,color:'#E76F24'/);
assert.match(bankSourceJs,/sampleRateHz:96000,fftSize:65536,maxFrequencyHz:48000,color:'#43A047'/);
assert.match(bankSourceJs,/sampleRateHz:192000,fftSize:131072,maxFrequencyHz:96000,color:'#E24A4A'/);
assert.match(bankFileJs,/api\.registerMeasurementSource\?\.\(entry\)/);
assert.doesNotMatch(bankFileJs,/bank-file-swatch/);
assert.match(pipelineJs,/#FF2D95','#8BD600','#563CFF'/);
assert.match(pipelineJs,/bankFile:\{position:null\}/);
assert.match(pipelineJs,/function positionMeasurementNode\(x,y\)/);
assert.match(pipelineJs,/function positionBankFileNode\(x,y\)/);
assert.match(pipelineJs,/function startBankFileDrag\(event\)/);
assert.match(pipelineJs,/function hideEmptyStateAnimated\(\)/);
assert.match(pipelineJs,/void emptyState\.offsetWidth;/);
assert.match(pipelineJs,/function showEmptyState\(\)/);
assert.match(pipelineJs,/emptyState\.addEventListener\('animationend'/);
assert.doesNotMatch(pipelineJs,/positionMeasurementStack/);
assert.match(pipelineJs,/registeredMeasurementSources\.get\(id\)/);
assert.doesNotMatch(pipelineCss,/\.pipeline-canvas-divider/);
assert.match(pipelineCss,/\.pipeline-strip\{[^}]*top:4px/);
assert.match(themeCss,/\.workspace-menu\{\s*top:4px!important;/);
assert.match(pipelineCss,/\.pipeline-node-canvas\{[^}]*inset:50px 0 0 0;[^}]*contain:layout paint style;isolation:isolate/);
assert.match(pipelineCss,/\.pipeline-canvas-controls\{[^}]*top:60px/);
assert.match(workspaceThemeJs,/const NODE_TOP_GAP_PX=8/);
assert.match(workspaceThemeJs,/const NODE_TOP_FALLBACK_PX=46/);
assert.match(workspaceThemeJs,/function nodeTopBoundary\(\)/);
assert.match(workspaceThemeJs,/controlsRect\.bottom-canvasRect\.top\+NODE_TOP_GAP_PX/);
assert.match(workspaceThemeJs,/Math\.ceil\(\(canvas\.scrollTop\+viewportClearance\)\/zoom\)/);
assert.match(workspaceThemeJs,/const visualLogicalY=Math\.max\(nodeTopBoundary\(\),requestedLogicalY\)/);
assert.match(workspaceThemeJs,/nodeTopBoundary,\s*positionNode,/);
assert.match(pipelineCss,/\.pipeline-node-empty\.is-exiting\{[^}]*animation:pipeline-empty-slide-left 420ms/);
assert.doesNotMatch(pipelineCss,/prefers-reduced-motion/);
assert.doesNotMatch(pipelineContextCss,/prefers-reduced-motion/);
assert.doesNotMatch(mpgdCss,/prefers-reduced-motion/);
assert.doesNotMatch(read('gui/matching/matching.js'),/prefers-reduced-motion/);
assert.match(pipelineContextCss,/\.pipeline-persistent-wire\{[^}]*stroke-width:2\.4;/);
assert.match(pipelineCss,/\.pipeline-wire-preview\{[^}]*stroke-width:2\.4;/);
assert.match(pipelineContextCss,/\.pipeline-wire-inspect-path\{[^}]*stroke-width:3\.84;/);
assert.match(pipelineContextCss,/\.pipeline-wire-inspect-path\.is-hover\{stroke-width:3\.36;/);
assert.doesNotMatch(pipelineContextCss,/raptor-wire-current|\.pipeline-wire-flow|\.pipeline-wire-inspect-flow/);
for(const source of [crossoverJs,mpgdJs,targetExportJs]){
  assert.doesNotMatch(source,/pipeline-wire-flow/);
}
assert.match(wireInspectJs,/canvas\.addEventListener\('pointerdown'/);
assert.match(wireInspectJs,/lockedWireId=wireId;[\s\S]*?scheduleRender\(\);/);
assert.doesNotMatch(wireInspectJs,/canvas\.addEventListener\('click'/);

console.log('RESULT RAPTOR pipeline visual contract PASS');
